#!/bin/bash
aws cloudformation package --template-file ../template.yaml --s3-bucket accountemplates --output-template-file out.yml
aws cloudformation deploy --template-file out.yml --stack-name msv-account-credit --capabilities CAPABILITY_NAMED_IAM